########################################
# file:	datatypes/Makefile
########################################

include ../MCONFIG

all: binary

.PHONY: binary

binary:
	$(CC) $(CFLAGS) $(DEFS) main.c -o ../.bin/datatypes -L../.lib -ldh

